# Generated by Django 3.0.8 on 2020-07-19 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='created',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 13, 2, 2, 800377, tzinfo=utc)),
        ),
    ]
